# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/oztools',
                'doc_host': 'https://ozellpaukert.github.io',
                'git_url': 'https://github.com/ozellpaukert/oztools',
                'lib_path': 'oztools'},
  'syms': { 'oztools.core': { 'oztools.core.attrkey': ('api/core.html#attrkey', 'oztools/core.py'),
                              'oztools.core.cz': ('api/core.html#cz', 'oztools/core.py'),
                              'oztools.core.pad': ('api/core.html#pad', 'oztools/core.py'),
                              'oztools.core.str_enumerate': ('api/core.html#str_enumerate', 'oztools/core.py')},
            'oztools.gh': { 'oztools.gh.commit_and_push': ('api/gh.html#commit_and_push', 'oztools/gh.py'),
                            'oztools.gh.gh_licenses': ('api/gh.html#gh_licenses', 'oztools/gh.py'),
                            'oztools.gh.gh_new_repo': ('api/gh.html#gh_new_repo', 'oztools/gh.py'),
                            'oztools.gh.gh_new_repo_fn': ('api/gh.html#gh_new_repo_fn', 'oztools/gh.py')},
            'oztools.kgl': { 'oztools.kgl.disp_comp': ('api/kgl.html#disp_comp', 'oztools/kgl.py'),
                             'oztools.kgl.kgl_hello': ('api/kgl.html#kgl_hello', 'oztools/kgl.py'),
                             'oztools.kgl.kgl_list': ('api/kgl.html#kgl_list', 'oztools/kgl.py')},
            'oztools.nbd': {'oztools.nbd.nbd_new': ('api/nbd.html#nbd_new', 'oztools/nbd.py')}}}
