# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/oztools',
                'doc_host': 'https://ozellpaukert.github.io',
                'git_url': 'https://github.com/ozellpaukert/oztools',
                'lib_path': 'oztools'},
  'syms': {'oztools.core': {'oztools.core.foo': ('core.html#foo', 'oztools/core.py')}}}
