"""Command line utilities for github"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/01_gh.ipynb.

# %% auto 0
__all__ = ['configpath', 'config', 'gh_username', 'token', 'api', 'gh_licenses', 'gh_new_repo']

# %% ../nbs/api/01_gh.ipynb 3
from fastcore.all import *
import itertools as it
import os
from ghapi.all import *

import configparser
from pathlib import Path

from .core import *

# %% ../nbs/api/01_gh.ipynb 5
configpath = Path("~/.gitconfig").expanduser()

config = configparser.ConfigParser()
config.read(configpath)

gh_username = config['user']['name']

token = os.environ["GITHUB_TOKEN"]

api = GhApi(owner=gh_username, token=token)

# %% ../nbs/api/01_gh.ipynb 6
@call_parse
def gh_licenses():
    "List GitHub license templates"
    l = api.licenses.get_all_commonly_used(per_page=100)
    #return l.attrgot("spdx_id")
    return "\n".join(l.map(lambda x: f"{pad(x['spdx_id'],16)}{pad(x['name'],42)}"))

# %% ../nbs/api/01_gh.ipynb 7
@call_parse
def gh_new_repo(name, description, license="Apache-2.0", private=False):
    "Create a new github repo and clone it"
    repo = api.repos.create_for_authenticated_user(name, description, private=private, license_template=license)
    from git import Repo
    cloned = Repo.clone_from(repo.ssh_url, repo.name)
    #os.chdir(repo.name)
