"""Command line utilities for github"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/01_gh.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/api/01_gh.ipynb 3
from fastcore.all import *
import itertools as it
import os
from ghapi.all import *
