"""Command line utilities for kaggle competitions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/03_kgl.ipynb.

# %% auto 0
__all__ = ['disp_comp', 'kgl_list', 'kgl_hello']

# %% ../nbs/api/03_kgl.ipynb 3
from fastcore.all import *
from fastkaggle import *
import itertools as it

from .core import *

# %% ../nbs/api/03_kgl.ipynb 6
def disp_comp(comp):
    slug = comp.url.split("/")[-1]
    return f"{pad(slug[:40],40)} {comp.title[:40]}"

# %% ../nbs/api/03_kgl.ipynb 9
@call_parse
def kgl_list():
    "List kaggle competitions"

    api = import_kaggle()
    comps = api.competitions_list()
    
    joinedkey = attrkey("userHasEntered")
    comps.sort(key=joinedkey)
    active, entered = (list(y) for x,y in it.groupby(comps, joinedkey))

    return '\n'.join(("Joined:", *str_enumerate(map(disp_comp, entered), 1),
                      "Active:", *str_enumerate(map(disp_comp, active), 1+len(entered))))

# %% ../nbs/api/03_kgl.ipynb 11
@call_parse
def kgl_hello():
    import os
    return os.getcwd()
